version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
    - "5432:5432"
    volumes:
    - lab_postgres_volume:/data/postgres
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
    - "8080:80"
    networks:
    - postgres

volumes:
  lab_postgres_volume:
 
networks:
  postgres:
    driver: bridge